meshery-extensions/meshery-nginx-sm

- .github/workflows/ci.yml
> [CI] establish edge release

- .github/workflows/ci.yml
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
> Change golangci-lint version to v1.32

- .github/ISSUE_TEMPLATE/documentation.md
- .github/config.yml
- .github/workflows/slack.yml
Changing layer5 link to meshery link
> Changing to meshery org

- .github/workflows/slack.yml
Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>
Changed the layer5 link to meshery link.
> Changing the meshery org

- internal/config/config.go
Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>
SMP protos compliant operation name for nginx
> SMP protos compliant operation name for nginx

- internal/config/releases.go
Signed-off-by: Shreyas220 <shreyas.ny@gmail.com>
changed the regexp to get version 
> adapter was unable to get version 

- .github/depedabot.yml
- helpers/component_info.json
- nginx/install.go
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>
Breaking installation due to presence/absence of a `v` prefix in appVersion shouldn't bother now.
> [lifecycle] convert app version to chart version manually

- .github/workflows/build-and-release.yml
- Dockerfile
- README.md
Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>
Support for build version at build time for this adaptor
This PR fixes #43 
> [Chore] Support for adaptor version at build time

- .github/workflows/update-oam-defs.yml
> [CI] add pattern components generator workflow

- .github/label-commenter-config.yml
- .github/workflows/label-commenter.yml
Signed-off-by: ruhi09 <rim.sen5613@gmail.com>
This PR fixes #38 
> Updated the workflow

- go.mod
- go.sum
- nginx/error.go
- nginx/oam.go
- templates/oam/workloads/nginxmesh.meshery.layer5io.schema.json
- templates/oam/workloads/nginxmesh_definition.json
> Added OAM components handling

- Dockerfile
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>
This PR is related to meshery/meshery#4642
Still WIP and subject to tests
> [WIP] Change version tags to fix CVEs

- .github/workflows/newcomers-alert.yml
Signed-off-by: Ankita Pareek <ankitapareek2000@gmail.com>
- This PR adds a workflow to notify about good first issues on the #newcomer slack channel of Layer5.
- The slack.yml file is already up-to-date.
This PR fixes #67 
> Added newcomers-alert.yml file to notify about good first issues on slack

- .github/install/deploy.yaml
- .github/workflows/e2etests.yaml
- nginx/install.go
> Added e2e tests

- .github/workflows/e2etests.yaml
> [E2E workflow]Create the directory if doesn't exist

- .github/workflows/update-oam-defs.yml
- templates/oam/workloads/v1.2.0/circuitbreaker.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.2.0/httproutegroup.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.2.0/ratelimit.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.2.0/tcproute.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.2.0/trafficsplit.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.2.0/traffictarget.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.2.1/circuitbreaker.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.2.1/httproutegroup.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.2.1/ratelimit.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.2.1/tcproute.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.2.1/trafficsplit.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.2.1/traffictarget.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.3.1/circuitbreaker.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.3.1/httproutegroup.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.3.1/ratelimit.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.3.1/spiffeid.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.3.1/tcproute.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.3.1/trafficsplit.nginx-sm.meshery.layer5io.schema.json
- templates/oam/workloads/v1.3.1/traffictarget.nginx-sm.meshery.layer5io.schema.json
> Added missing "title" fields in schema

- main.go
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>
Should fix the issue getting version on UI.
This PR fixes #86 
> should fix version problem

- README.md
Signed-off-by: Swapnil Bhabal <swapnilbhabal787@gmail.com>
fixed #69 
> Discourse shield is added.

- nginx/error.go
Signed-off-by: asubedy <frexpe@pm.me>
> enhanced OAM error message

- go.mod
- go.sum
- nginx/install.go
> Meshkit dependency update 

- helpers/component_info.json
- internal/config/error.go
- nginx/error.go
> Fix duplicate error codes

- go.mod
- go.sum
- nginx/custom_operation.go
- nginx/error.go
- nginx/install.go
- nginx/nginx.go
- nginx/oam.go
- nginx/sample_apps.go
Signed-off-by: Ruturaj Mohite <mohite.ruturaj15@gmail.com>
Adds multi context support to Nginx SM
> Multi Context Refactor

- .github/workflows/build-and-release.yml
> update go version

- Dockerfile
> Nginx SM: Remove arch hardcode and kubeopenapi-jsonschema

- go.mod
- go.sum
- nginx/nginx.go
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>
This PR enables sending complete error details to client;
1. Error Code
2. Cause
3. Remedy
4. Component Type
5. Component Name 
> Send detailed error response to client

- .github/workflows/multi-platform.yml
Signed-off-by: PiotrLewandowski323 <lewandowski323@gmail.com>
This PR fixes #160 
> update multiplatform build and release workflow

- .github/workflows/e2etests.yaml
This PR fixes #260 it implments specific e2e test fix in the [workflow](https://github.com/meshery/meshery-nginx-sm/actions/runs/6181775040)
> switching node version
